networks:
  rag_network:
    driver: bridge

volumes:
  mongo_data:
  chromadb_data:
    driver: local
  ollama_data:

services:
  # --- BANCO DE DADOS NOSQL (METADADOS COM AUTENTICAÇÃO) ---
  mongodb:
    image: mongo:6.0
    container_name: cognifiles_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret_password
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - rag_network

  # --- MOTOR DE INFERÊNCIA LOCAL (LLM) ---
  ollama:
    image: ollama/ollama:latest
    container_name: rag_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - rag_network

  # --- BACKEND API (FASTAPI) ---
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: rag_backend
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/app/.chromadb_storage
    environment:
      - MONGO_URI=mongodb://admin:secret_password@mongodb:27017/?authSource=admin
      - LOCAL_LLM_URL=http://ollama:11434
      - LOCAL_MODEL_NAME=llama3.2:1b
      - CHROMA_PERSIST_DIR=/app/.chromadb_storage
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - rag_network

  # --- FRONTEND (STREAMLIT) ---
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: rag_frontend
    ports:
      - "8501:8501"
    volumes:
      - ./app_frontend.py:/app/app_frontend.py  # 🌟 Espelha o teu ficheiro da máquina local para dentro do Docker
    environment:
      - BASE_URL=http://backend:8000/api/v1     # 🌟 URL interna da rede Docker
    depends_on:
      - backend
    networks:
      - rag_network