FROM python:3.11-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

COPY pyproject.toml uv.lock ./

# CRUCIAL: Garante o arquivo fake aqui também
RUN touch README.md

RUN /bin/uv sync --frozen --no-install-project --no-dev

COPY app_frontend.py .

EXPOSE 8501

CMD ["/bin/uv", "run", "streamlit", "run", "app_frontend.py", "--server.port", "8501", "--server.address", "0.0.0.0"]