from __future__ import annotations
from datetime import datetime
from pydantic import BaseModel, Field, ConfigDict


class ChatMessageSchema(BaseModel):
    """Represents a single message exchange within a chat session context."""

    role: str = Field(
        ..., description="The author of the message: 'user', 'assistant', or 'system'."
    )
    content: str = Field(
        ..., min_length=1, description="The textual content of the message."
    )
    timestamp: datetime = Field(
        default_factory=datetime.now, description="When the message was registered."
    )


class QueryRequest(BaseModel):
    """Payload template sent by the client to query the RAG engine."""

    prompt: str = Field(
        ..., min_length=1, description="The question or command sent to the model."
    )
    collection_name: str = Field(
        ...,
        min_length=3,
        description="The targeted ChromaDB collection for context retrieval.",
    )
    history: list[ChatMessageSchema] = Field(  # type: ignore
        default_factory=list, description="Previous messages for conversational memory."
    )


class QueryResponse(BaseModel):
    """The strict typed interface returned by the API containing the answer and source context."""

    answer: str = Field(
        ..., description="The final text response generated by the orchestrated LLM."
    )
    provider_used: str = Field(
        ...,
        description="Indicates if the response came from 'gemini' or 'ollama-fallback'.",
    )
    retrieved_contexts: list[str] = Field(
        ...,
        description="The raw text chunks extracted from ChromaDB used to feed the prompt.",
    )
    executed_at: datetime = Field(default_factory=datetime.now)

    model_config = ConfigDict(from_attributes=True)
